<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Util.fs" />
    <Compile Include="FSharpPlusTests.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FSharpPlus" Version="1.9.1" />
    <PackageReference Update="FSharp.Core" Version="10.1.401" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libs\Hopac\Hopac.fsproj" />
    <ProjectReference Include="..\..\Libs\Hopac.Core\Hopac.Core.csproj" />
    <ProjectReference Include="..\..\Libs\Hopac.Platform\Hopac.Platform.fsproj" />
  </ItemGroup>

</Project>
