<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DebugType>Embedded</DebugType>
    <EmbedAllSources>True</EmbedAllSources>
    <OtherFlags>--warnon:1182</OtherFlags>
    <NoWarn>FS0044;FS0057</NoWarn>
    <PackageId>HopacPlus</PackageId>
    <PackageVersion Condition="'$(PackageVersion)' == ''">0.1.0</PackageVersion>
    <Version>$(PackageVersion)</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>Enrique Casanovas</Authors>
    <Company>The Otter Side</Company>
    <Description>Hopac is a library for higher-Order, parallel, asynchronous and concurrent programming in F#.

Inspired by languages like Concurrent ML and Cilk, Hopac is a library for F# with the aim of making it easier to write efficient parallel, asynchronous, concurrent and reactive programs. Hopac is licensed under a MIT-style license. See project website for further information.

This package is a fork of the original Hopac library by Vesa Karvonen.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>© 2016 Vesa Karvonen, 2018 Open Source Contributors, The Otter Side</Copyright>
    <PackageTags>F#;FSharp;Hopac;Hopac+;F#+;FSharpPlus;concurrency</PackageTags>
    <PackageProjectUrl>https://github.com/eacasanovaspedre/Hopac</PackageProjectUrl>
    <RepositoryUrl>https://github.com/eacasanovaspedre/Hopac</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <Compile Include="Util.fs" />
    <Compile Include="Hopac.fsi" />
    <Compile Include="Hopac.fs" />
    <Compile Include="Stream.fsi" />
    <Compile Include="Stream.fs" />
    <Compile Include="TopLevel.fsi" />
    <Compile Include="TopLevel.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="FSharp.Core" Version="10.1.401" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hopac.Core\Hopac.Core.csproj">
      <PrivateAssets>all</PrivateAssets>
    </ProjectReference>
    <ProjectReference Include="..\Hopac.Platform\Hopac.Platform.fsproj">
      <PrivateAssets>all</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="$(OutDir)\Hopac.Core.dll">
      <PackagePath>lib\netstandard2.1\</PackagePath>
      <Pack>true</Pack>
    </Content>
    <Content Include="$(OutDir)\Hopac.Core.pdb">
      <PackagePath>lib\netstandard2.1\</PackagePath>
      <Pack>true</Pack>
    </Content>
    <Content Include="$(OutDir)\Hopac.Core.xml">
      <PackagePath>lib\netstandard2.1\</PackagePath>
      <Pack>true</Pack>
    </Content>
    <Content Include="$(OutDir)\Hopac.Platform.dll">
      <PackagePath>lib\netstandard2.1\</PackagePath>
      <Pack>true</Pack>
    </Content>
    <Content Include="$(OutDir)\Hopac.Platform.pdb">
      <PackagePath>lib\netstandard2.1\</PackagePath>
      <Pack>true</Pack>
    </Content>
    <Content Include="$(OutDir)\Hopac.Platform.xml">
      <PackagePath>lib\netstandard2.1\</PackagePath>
      <Pack>true</Pack>
    </Content>
  </ItemGroup>
  
</Project>
